FROM node:22 AS builder

WORKDIR /app

ARG VITE_BACKEND_BASE_URL
ARG VITE_SYSTEM_VERSION
ARG VITE_CARD_ID_FIXED

ENV VITE_BACKEND_BASE_URL=$VITE_BACKEND_BASE_URL
ENV VITE_SYSTEM_VERSION=$VITE_SYSTEM_VERSION
ENV VITE_CARD_ID_FIXED=$VITE_CARD_ID_FIXED

COPY package.json yarn.lock ./
RUN yarn install

COPY . .

RUN yarn build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]