services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://${DATABASE_HOST}:3306/${DATABASE_DB}
    networks:
      - public
      - private
    depends_on:
      - db
      # - storage
  db:
    image: mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
      - ./db/export:/var/lib/mysql-files
      - ./db/scripts:/aux-scripts
    ports:
      - 3307:3306
    networks:
      - private
    environment:
      - MYSQL_DATABASE=${DATABASE_DB}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD_ROOT}
  # storage:
  #   build:
  #     context: ./storage
  #     dockerfile: dockerfile
  #   ports:
  #     - "9023:9023"
  #   volumes:
  #     - storage-data:/home
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
      args:
        VITE_BACKEND_BASE_URL: ${VITE_BACKEND_BASE_URL}
        VITE_SYSTEM_VERSION: ${VITE_SYSTEM_VERSION}
        VITE_ORDER_CARD_ID_FIXED: ${VITE_ORDER_CARD_ID_FIXED}
        VITE_CASH_REGISTER_UUID_FIXED: ${VITE_CASH_REGISTER_UUID_FIXED}
    env_file:
      - .env
    ports:
      - "80:80"
    networks:
      - public
    depends_on:
      - backend
  # table_service:
  #   build:
  #     context: ./table_service
  #     dockerfile: dockerfile
  #   container_name: table-service-container
  #   networks:
  #     - private
  #   restart: unless-stopped
  #   volumes:
  #     - ./app:/app
  #   command: python main.py
networks:
  public:
  private:
volumes:
  db-data:
  # storage-data:
