services:
  backend:
    build:
      args:
      - NODE_ENV=development
      context: backend
      target: development
    command: npm run start-watch
    environment:
      - DATABASE_DB=store_control
      - DATABASE_USER=root
      - DATABASE_PASSWORD=/run/secrets/db-password
      - DATABASE_HOST=db
      - SECRET_TOKEN=jashduwqekckweasd
      - NODE_ENV=development
    ports:
      - 80:80
      # - 9229:9229
      # - 9230:9230
    secrets:
      - db-password
    volumes:
      - backend-node:/opt/app/node_modules
      - ./backend/images:/code/images
      - ./backend/src:/code/src:ro
      - ./backend/codes:/code/codes:ro
      - ./backend/package.json:/code/package.json
      - ./backend/package-lock.json:/code/package-lock.json
    networks:
      - public
      - private
    depends_on:
      - db
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    # image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    image: mysql:8.0.33
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
      - ./db/store_control.sql:/docker-entrypoint-initdb.d/store_control.sql:ro
      - ./db/export:/var/lib/mysql-files
    networks:
      - private
    environment:
      - MYSQL_DATABASE=store_control
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
  frontend:
    build:
      context: frontend
      target: development
    ports:
      - 3000:3000
    volumes:
      - frontend-node:/code/node_modules
      - ./frontend/src:/code/src
      - ./frontend/package.json:/code/package.json
      - ./frontend/package-lock.json:/code/package-lock.json
    networks:
      - public
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
networks:
  public:
  private:
volumes:
  backend-node:
  db-data:
  frontend-node:
secrets:
  db-password:
    file: db/password.txt
