name: Build and Deploy Backend

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  build-and-deploy-backend:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Autenticar no GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configurar repo
        run: gcloud auth configure-docker ${{ vars.GCP_REPOSITORY_LOCATION }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: backend/
          push: true
          tags: ${{ vars.GCP_REPOSITORY_LOCATION }}/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCP_REPOSITORY_NAME }}/backend-spring-boot:${{ github.sha }}
