name: Build and Deploy Frontend

on:
  workflow_dispatch:

jobs:
  build-and-deploy-frontend:
    runs-on: "ubuntu-latest"
    env:
      VITE_BACKEND_BASE_URL: ${{ vars.VITE_BACKEND_BASE_URL }}
      VITE_SYSTEM_VERSION: ${{ vars.VITE_SYSTEM_VERSION }}
      VITE_ORDER_CARD_ID_FIXED: "OrderCardSimple"
      VITE_CASH_REGISTER_UUID_FIXED: "12345678-abcd-4efa-bcde-f1234567890a"
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Autenticar no GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: frontend/
          push: true
          tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend-react:${{ github.sha }}
