name: Build and Deploy Frontend

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths-ignore:
      - "backend/**"
      - "db/**"
      - "table_service/**"

jobs:
  build-and-deploy-frontend:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Autenticar no GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configurar repo
        run: gcloud auth configure-docker ${{ vars.GCP_REPOSITORY_LOCATION }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: frontend/
          push: true
          tags: ${{ vars.GCP_REPOSITORY_LOCATION }}/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCP_REPOSITORY_NAME }}/frontend-react:${{ github.sha }}
          build-args: |
            VITE_BACKEND_BASE_URL=${{ vars.VITE_BACKEND_BASE_URL }}
            VITE_SYSTEM_VERSION=${{ vars.VITE_SYSTEM_VERSION }}
            VITE_ORDER_CARD_ID_FIXED="OrderCardSimple"
            VITE_CASH_REGISTER_UUID_FIXED="12345678-abcd-4efa-bcde-f1234567890a"

      - name: Aguardar a disponibilidade da imagem
        run: sleep 10

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy frontend-react \
            --image=${{ vars.GCP_REPOSITORY_LOCATION }}/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCP_REPOSITORY_NAME }}/frontend-react:${{ github.sha }} \
            --region=${{ vars.GCP_REGION }} \
            --platform=managed \
            --allow-unauthenticated
