name: Test Backend

on:
  pull_request:
    branches:
      - dev
    paths-ignore:
      - "frontend/**"
      - "db/**"
      - "table_service/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test-backend:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"
          cache: "maven"
          cache-dependency-path: "backend/pom.xml"

      - name: Rodar testes com Maven
        run: mvn test --file backend/pom.xml
